server:
  port: 8086
  context-path: /qas-service

spring:
  datasource: # Database properties
    url: jdbc:h2:mem:wee_qas
  jpa: # JPA configuration
    show-sql: true
    hibernate:
      ddl-auto: validate

flyway: # Flyway properties
  url: ${spring.datasource.url}