spring:
  datasource: # Database properties
    url: jdbc:mysql://localhost:3306/wee_qas?useSSL=false
    username: root
    password:
    #driverClassName: com.mysql.cj.jdbc.Driver
  jpa: # JPA configuration
    show-sql: true
    hibernate:
      ddl-auto: validate
    #database-platform: org.hibernate.dialect.MySQL5Dialect
