server:
  port: 8086
  context-path: /qas-service

spring:
  datasource: # Database properties
    url: jdbc:h2:file:./tmp/wee_qas
    username: sa
    password:
  jpa: # JPA configuration
    show-sql: true
    hibernate:
      ddl-auto: validate

flyway: # Flyway properties
  url: ${spring.datasource.url}
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}