version: '2'

services:
  qas:
    build: .
    image: twwee/qas-service
    container_name: qas-node
    ports:
      - "8086:8086"
    networks:
      - wee-net
    volumes:
      - ../dist:/app

networks:
  wee-net:
    driver: bridge