version: '2'

services:
  qas:
    image: twwee/qas-service
    container_name: qas-node
    hostname: qas-service
    restart: always
    ports:
      - "8086:8086"
    networks:
      - wee-net
    volumes:
      - .:/app

networks:
  wee-net:
    driver: bridge