version: '2'

services:
  qas:
    image: java:openjdk-8-jre
    working_dir: /app
    volumes:
      - ../build/libs/:/app
    command: java -jar /app/qas-service-0.1.0.jar
    container_name: qas-node
    hostname: qas-service
    restart: always
    ports:
      - "8086:8086"
    networks:
      - wee-net

networks:
  wee-net:
    driver: bridge